{{- if .Values.persistence.cache.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  accessModes: {{ .Values.persistence.cache.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}