{{- if .Values.persistance.config.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistance.config.storageClass }}
  accessModes: {{ .Values.persistance.config.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistance.config.size }}
{{- end }}